project_name: terraform-provider-freebox
release:
  github:
    owner: darshaner
    name: terraform-provider-freebox

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: terraform-provider-freebox

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "terraform-provider-freebox_{{ .Version }}_SHA256SUMS"

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    args:
      [
        "--batch",
        "-u", "{{ .Env.GPG_FINGERPRINT }}",
        "--detach-sign",
        "--output", "${signature}",
        "${artifact}"
      ]


